// frontend/src/components/SearchBox.vue
<template>
  <div ref="searchContainer" :class="cn('relative', className)">
    <!-- Search Input -->
    <div class="relative">
      <input
        ref="searchInput"
        v-model="searchState.query"
        @input="handleInputChange"
        @focus="handleInputFocus"
        @keydown="handleKeyDown"
        type="text"
        placeholder="Search documentation..."
        class="w-full pl-10 pr-10 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-gray-100 placeholder-gray-500 dark:placeholder-gray-400 focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-colors"
      />
      
      <!-- Search Icon -->
      <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
        <LoadingSpinner v-if="searchState.isSearching" size="small" />
        <Search v-else class="h-5 w-5 text-gray-400" />
      </div>

      <!-- Clear Button -->
      <button
        v-if="searchState.query"
        @click="clearSearch"
        class="absolute inset-y-0 right-0 pr-3 flex items-center text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 transition-colors"
      >
        <X class="h-5 w-5" />
      </button>
    </div>

    <!-- Search Results Dropdown -->
    <div 
      v-if="searchState.isOpen" 
      class="absolute top-full left-0 right-0 mt-1 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg shadow-lg z-50 max-h-96 overflow-y-auto"
    >
      <!-- Error State -->
      <div v-if="searchState.error" class="p-4">
        <ErrorDisplay
          :error="searchState.error"
          title="Search Error"
          :on-retry="() => performSearch(searchState.query)"
          :show-retry="true"
          class="text-left"
        />
      </div>

      <!-- No Results -->
      <div 
        v-else-if="searchState.results.length === 0 && searchState.hasSearched" 
        class="p-4 text-center"
      >
        <div class="text-gray-400 dark:text-gray-600 mb-2">
          <Search class="h-8 w-8 mx-auto" />
        </div>
        <p class="text-sm text-gray-600 dark:text-gray-400">
          No results found for "{{ searchState.query }}"
        </p>
        <p class="text-xs text-gray-500 dark:text-gray-500 mt-1">
          Try different keywords or check your spelling
        </p>
      </div>

      <!-- Results -->
      <div v-else class="py-2">
        <button
          v-for="(result, index) in searchState.results"
          :key="`${result.doc_id}-${index}`"
          @click="handleResultClick(result)"
          class="w-full px-4 py-3 text-left hover:bg-gray-50 dark:hover:bg-gray-700 border-b border-gray-100 dark:border-gray-700 last:border-b-0 transition-colors focus:outline-none focus:bg-gray-50 dark:focus:bg-gray-700"
        >
          <div class="flex items-start space-x-3">
            <div class="flex-shrink-0 mt-1">
              <FileText class="h-4 w-4 text-gray-400" />
            </div>
            <div class="flex-1 min-w-0">
              <div class="flex items-center space-x-2 mb-1">
                <h4 class="text-sm font-medium text-gray-900 dark:text-gray-100 truncate">
                  {{ result.title }}
                </h4>
                <span :class="cn('inline-flex items-center px-2 py-0.5 rounded text-xs font-medium', getDocTypeColor(result.doc_type))">
                  {{ getDocTypeDisplayName(result.doc_type) }}
                </span>
              </div>
              <p class="text-sm text-gray-600 dark:text-gray-400 line-clamp-2">
                {{ result.content_snippet }}
              </p>
              <div class="flex items-center justify-between mt-2">
                <span class="text-xs text-gray-500 dark:text-gray-500">
                  Relevance: {{ Math.round(result.relevance_score * 100) }}%
                </span>
                <ExternalLink class="h-3 w-3 text-gray-400" />
              </div>
            </div>
          </div>
        </button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted, onUnmounted } from 'vue'
import { Search, X, FileText, ExternalLink } from 'lucide-vue-next'
import { api } from '@/lib/api'
import { cn } from '@/lib/utils'
import LoadingSpinner from './LoadingSpinner.vue'
import ErrorDisplay from './ErrorDisplay.vue'

interface Props {
  repoId: string
  onDocumentSelect: (docId: string) => void
  className?: string
}

interface SearchResult {
  doc_id: string
  title: string
  content_snippet: string
  relevance_score: number
  doc_type: string
  code_references: any[]
}

const props = withDefaults(defineProps<Props>(), {
  className: ''
})

const emit = defineEmits<{
  documentSelect: [docId: string]
}>()

const searchInput = ref<HTMLInputElement>()
const searchContainer = ref<HTMLDivElement>()
let debounceTimeout: NodeJS.Timeout | null = null

const searchState = reactive({
  query: '',
  results: [] as SearchResult[],
  isSearching: false,
  isOpen: false,
  error: null as string | null,
  hasSearched: false
})

// Cache for search results
const searchCache = new Map<string, SearchResult[]>()

const performSearch = async (query: string) => {
  if (!query.trim()) {
    searchState.results = []
    searchState.isOpen = false
    searchState.hasSearched = false
    searchState.error = null
    return
  }

  // Check cache first
  const cacheKey = `${props.repoId}:${query.toLowerCase()}`
  const cachedResults = searchCache.get(cacheKey)
  
  if (cachedResults) {
    searchState.results = cachedResults
    searchState.isOpen = true
    searchState.hasSearched = true
    searchState.error = null
    return
  }

  searchState.isSearching = true
  searchState.error = null

  try {
    const response = await api.searchDocuments({
      query: query.trim(),
      repo_id: props.repoId,
      limit: 10
    })

    // Cache the results
    searchCache.set(cacheKey, response.results)

    searchState.results = response.results
    searchState.isSearching = false
    searchState.isOpen = true
    searchState.hasSearched = true
    searchState.error = null
  } catch (error) {
    console.error('Search error:', error)
    searchState.isSearching = false
    searchState.isOpen = true
    searchState.hasSearched = true
    searchState.error = error instanceof Error ? error.message : 'Search failed'
  }
}

const handleInputChange = () => {
  // Clear existing timeout
  if (debounceTimeout) {
    clearTimeout(debounceTimeout)
  }

  // Set new timeout for debounced search
  debounceTimeout = setTimeout(() => {
    performSearch(searchState.query)
  }, 300)
}

const handleInputFocus = () => {
  if (searchState.hasSearched && searchState.results.length > 0) {
    searchState.isOpen = true
  }
}

const handleResultClick = (result: SearchResult) => {
  emit('documentSelect', result.doc_id)
  props.onDocumentSelect(result.doc_id)
  searchState.isOpen = false
  searchInput.value?.blur()
}

const clearSearch = () => {
  searchState.query = ''
  searchState.results = []
  searchState.isSearching = false
  searchState.isOpen = false
  searchState.error = null
  searchState.hasSearched = false
  searchInput.value?.focus()
}

const handleKeyDown = (event: KeyboardEvent) => {
  if (event.key === 'Escape') {
    searchState.isOpen = false
    searchInput.value?.blur()
  }
}

const getDocTypeDisplayName = (docType: string): string => {
  switch (docType) {
    case 'system_overview':
      return 'System Overview'
    case 'component_profile':
      return 'Component Profile'
    case 'flow_threat_model':
      return 'Flow Model'
    case 'mitigation':
      return 'Mitigation'
    default:
      return 'Document'
  }
}

const getDocTypeColor = (docType: string): string => {
  switch (docType) {
    case 'system_overview':
      return 'bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200'
    case 'component_profile':
      return 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200'
    case 'flow_threat_model':
      return 'bg-purple-100 text-purple-800 dark:bg-purple-900 dark:text-purple-200'
    case 'mitigation':
      return 'bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200'
    default:
      return 'bg-gray-100 text-gray-800 dark:bg-gray-900 dark:text-gray-200'
  }
}

// Handle clicks outside to close search results
const handleClickOutside = (event: MouseEvent) => {
  if (searchContainer.value && !searchContainer.value.contains(event.target as Node)) {
    searchState.isOpen = false
  }
}

onMounted(() => {
  document.addEventListener('mousedown', handleClickOutside)
})

onUnmounted(() => {
  document.removeEventListener('mousedown', handleClickOutside)
  if (debounceTimeout) {
    clearTimeout(debounceTimeout)
  }
})
</script>

// frontend/src/components/SearchBox.tsx
'use client';

import { useState, useEffect, useRef } from 'react';
import { Search, X, FileText, ExternalLink } from 'lucide-react';
import { api } from '@/lib/api';
import { SearchResult, ThreatDocType } from '@/lib/types';
import LoadingSpinner from './LoadingSpinner';

interface SearchBoxProps {
  repoId: string;
  onDocumentSelect: (docId: string) => void;
  className?: string;
}

interface SearchState {
  query: string;
  results: SearchResult[];
  isSearching: boolean;
  isOpen: boolean;
  error: string | null;
  hasSearched: boolean;
}

// Cache for search results to avoid repeated API calls
const searchCache = new Map<string, SearchResult[]>();

export default function SearchBox({ repoId, onDocumentSelect, className = '' }: SearchBoxProps) {
  const [searchState, setSearchState] = useState<SearchState>({
    query: '',
    results: [],
    isSearching: false,
    isOpen: false,
    error: null,
    hasSearched: false
  });

  const searchInputRef = useRef<HTMLInputElement>(null);
  const searchContainerRef = useRef<HTMLDivElement>(null);
  const debounceTimeoutRef = useRef<NodeJS.Timeout | null>(null);

  // Handle clicks outside to close search results
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (searchContainerRef.current && !searchContainerRef.current.contains(event.target as Node)) {
        setSearchState(prev => ({ ...prev, isOpen: false }));
      }
    };

    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  // Debounced search function
  const performSearch = async (query: string) => {
    if (!query.trim()) {
      setSearchState(prev => ({
        ...prev,
        results: [],
        isOpen: false,
        hasSearched: false,
        error: null
      }));
      return;
    }

    // Check cache first
    const cacheKey = `${repoId}:${query.toLowerCase()}`;
    const cachedResults = searchCache.get(cacheKey);
    
    if (cachedResults) {
      setSearchState(prev => ({
        ...prev,
        results: cachedResults,
        isOpen: true,
        hasSearched: true,
        error: null
      }));
      return;
    }

    setSearchState(prev => ({ ...prev, isSearching: true, error: null }));

    try {
      const response = await api.searchDocuments({
        query: query.trim(),
        repo_id: repoId,
        limit: 10
      });

      // Cache the results
      searchCache.set(cacheKey, response.results);

      setSearchState(prev => ({
        ...prev,
        results: response.results,
        isSearching: false,
        isOpen: true,
        hasSearched: true,
        error: null
      }));
    } catch (error) {
      console.error('Search error:', error);
      setSearchState(prev => ({
        ...prev,
        isSearching: false,
        isOpen: true,
        hasSearched: true,
        error: error instanceof Error ? error.message : 'Search failed'
      }));
    }
  };

  // Handle input changes with debouncing
  const handleInputChange = (value: string) => {
    setSearchState(prev => ({ ...prev, query: value }));

    // Clear existing timeout
    if (debounceTimeoutRef.current) {
      clearTimeout(debounceTimeoutRef.current);
    }

    // Set new timeout for debounced search
    debounceTimeoutRef.current = setTimeout(() => {
      performSearch(value);
    }, 300);
  };

  // Handle search input focus
  const handleInputFocus = () => {
    if (searchState.hasSearched && searchState.results.length > 0) {
      setSearchState(prev => ({ ...prev, isOpen: true }));
    }
  };

  // Handle result selection
  const handleResultClick = (result: SearchResult) => {
    onDocumentSelect(result.doc_id);
    setSearchState(prev => ({ ...prev, isOpen: false }));
    searchInputRef.current?.blur();
  };

  // Clear search
  const clearSearch = () => {
    setSearchState({
      query: '',
      results: [],
      isSearching: false,
      isOpen: false,
      error: null,
      hasSearched: false
    });
    searchInputRef.current?.focus();
  };

  // Handle keyboard navigation
  const handleKeyDown = (event: React.KeyboardEvent) => {
    if (event.key === 'Escape') {
      setSearchState(prev => ({ ...prev, isOpen: false }));
      searchInputRef.current?.blur();
    }
  };

  // Get document type display name
  const getDocTypeDisplayName = (docType: ThreatDocType): string => {
    switch (docType) {
      case ThreatDocType.SYSTEM_OVERVIEW:
        return 'System Overview';
      case ThreatDocType.COMPONENT_PROFILE:
        return 'Component Profile';
      case ThreatDocType.FLOW_THREAT_MODEL:
        return 'Flow Model';
      case ThreatDocType.MITIGATION:
        return 'Mitigation';
      default:
        return 'Document';
    }
  };

  // Get document type color
  const getDocTypeColor = (docType: ThreatDocType): string => {
    switch (docType) {
      case ThreatDocType.SYSTEM_OVERVIEW:
        return 'bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200';
      case ThreatDocType.COMPONENT_PROFILE:
        return 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200';
      case ThreatDocType.FLOW_THREAT_MODEL:
        return 'bg-purple-100 text-purple-800 dark:bg-purple-900 dark:text-purple-200';
      case ThreatDocType.MITIGATION:
        return 'bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200';
      default:
        return 'bg-gray-100 text-gray-800 dark:bg-gray-900 dark:text-gray-200';
    }
  };

  // Highlight search terms in text
  const highlightSearchTerms = (text: string, query: string): React.ReactNode => {
    if (!query.trim()) return text;

    const terms = query.toLowerCase().split(/\s+/).filter(term => term.length > 0);
    let highlightedText = text;

    terms.forEach(term => {
      const regex = new RegExp(`(${term})`, 'gi');
      highlightedText = highlightedText.replace(regex, '<mark class="bg-yellow-200 dark:bg-yellow-800 px-0.5 rounded">$1</mark>');
    });

    return <span dangerouslySetInnerHTML={{ __html: highlightedText }} />;
  };

  return (
    <div ref={searchContainerRef} className={`relative ${className}`}>
      {/* Search Input */}
      <div className="relative">
        <input
          ref={searchInputRef}
          type="text"
          value={searchState.query}
          onChange={(e) => handleInputChange(e.target.value)}
          onFocus={handleInputFocus}
          onKeyDown={handleKeyDown}
          placeholder="Search documentation..."
          className="w-full pl-10 pr-10 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-gray-100 placeholder-gray-500 dark:placeholder-gray-400 focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-colors"
        />
        
        {/* Search Icon */}
        <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
          {searchState.isSearching ? (
            <LoadingSpinner size="small" />
          ) : (
            <Search className="h-5 w-5 text-gray-400" />
          )}
        </div>

        {/* Clear Button */}
        {searchState.query && (
          <button
            onClick={clearSearch}
            className="absolute inset-y-0 right-0 pr-3 flex items-center text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 transition-colors"
          >
            <X className="h-5 w-5" />
          </button>
        )}
      </div>

      {/* Search Results Dropdown */}
      {searchState.isOpen && (
        <div className="absolute top-full left-0 right-0 mt-1 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg shadow-lg z-50 max-h-96 overflow-y-auto">
          {searchState.error ? (
            <div className="p-4 text-center">
              <div className="text-red-600 dark:text-red-400 mb-2">
                <FileText className="h-8 w-8 mx-auto" />
              </div>
              <p className="text-sm text-red-600 dark:text-red-400">
                {searchState.error}
              </p>
            </div>
          ) : searchState.results.length === 0 && searchState.hasSearched ? (
            <div className="p-4 text-center">
              <div className="text-gray-400 dark:text-gray-600 mb-2">
                <Search className="h-8 w-8 mx-auto" />
              </div>
              <p className="text-sm text-gray-600 dark:text-gray-400">
                No results found for "{searchState.query}"
              </p>
              <p className="text-xs text-gray-500 dark:text-gray-500 mt-1">
                Try different keywords or check your spelling
              </p>
            </div>
          ) : (
            <div className="py-2">
              {searchState.results.map((result, index) => (
                <button
                  key={`${result.doc_id}-${index}`}
                  onClick={() => handleResultClick(result)}
                  className="w-full px-4 py-3 text-left hover:bg-gray-50 dark:hover:bg-gray-700 border-b border-gray-100 dark:border-gray-700 last:border-b-0 transition-colors focus:outline-none focus:bg-gray-50 dark:focus:bg-gray-700"
                >
                  <div className="flex items-start space-x-3">
                    <div className="flex-shrink-0 mt-1">
                      <FileText className="h-4 w-4 text-gray-400" />
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center space-x-2 mb-1">
                        <h4 className="text-sm font-medium text-gray-900 dark:text-gray-100 truncate">
                          {result.title}
                        </h4>
                        <span className={`inline-flex items-center px-2 py-0.5 rounded text-xs font-medium ${getDocTypeColor(result.doc_type)}`}>
                          {getDocTypeDisplayName(result.doc_type)}
                        </span>
                      </div>
                      <p className="text-sm text-gray-600 dark:text-gray-400 line-clamp-2">
                        {highlightSearchTerms(result.content_snippet, searchState.query)}
                      </p>
                      <div className="flex items-center justify-between mt-2">
                        <span className="text-xs text-gray-500 dark:text-gray-500">
                          Relevance: {Math.round(result.relevance_score * 100)}%
                        </span>
                        <ExternalLink className="h-3 w-3 text-gray-400" />
                      </div>
                    </div>
                  </div>
                </button>
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
